### PR TITLE
Remove `zeitwerk` and Opal compatibility

### LINKED ISSUE #6: Zeitwerk incompatible with Opal
Unable to use Plurimath-Js due to `zeitwerk`.

The [line](https://github.com/plurimath/plurimath-js/blob/master/src/index.ts#L3) `Opal.require("plurimath");` fails.

### PR DESCRIPTION
**Pull request by suleman-uzair**
This PR removes `zeitwerk` dependency, updates the attribute definition strucutre.

closes #6 
related => plurimath/plurimath-js#35

### CODE REVIEW

**Comment by suleman-uzair** [comment]
This PR depends on:
1. lutaml/lutaml-model#340
2. lutaml/moxml#17

**Comment by suleman-uzair** [comment]
@ronaldtse, This PR is a workaround for the circular dependency fix only for the successful release of **Plurimath-JS**.
I have created issue **lutaml/lutaml-model#339**, in my POV, implementation of this enhancement in **LutaML-Model** should help in fixing the circular dependency issue.

File: lib/mml.rb [hunk 1]
```diff
@@ -1,7 +1,14 @@
 # frozen_string_literal: true
 
-require "zeitwerk"
 require "lutaml/model"
+require "mml/configuration"
+if RUBY_ENGINE == "opal"
+  require_relative "mml/opal_setup"
+else
+  files = Dir["lib/mml/*.rb"].reject { |file| File.basename(file, ".*") == "common_attributes" }
+  files.each { |file| require "mml/#{File.basename(file, ".rb")}" }
```
Comment (ronaldtse) [inline lib/mml.rb:9]: Can you use `require_relative`?

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@suleman-uzair please feel free to merge when ready, thanks!

**Review by ronaldtse — APPROVED** [review]
@suleman-uzair please feel free to merge. Thanks!
